server:
  host: 0.0.0.0
  port: 8000
  use_ngrok: false
  use_auth: false
  auth_username: user
  auth_password: password
  log_file_path: logs/tts_server.log
  log_file_max_size_mb: 10
  log_file_backup_count: 5
model:
  repo_id: chatterbox-multilingual
tts_engine:
  device: cuda
  predefined_voices_path: voices
  reference_audio_path: reference_audio
  default_voice_id: Kustosz.wav
paths:
  model_cache: model_cache
  output: outputs
generation_defaults:
  temperature: 0.6
  exaggeration: 0.5
  cfg_weight: 0.5
  seed: 0
  speed_factor: 1.0
  sentence_pause_ms: 250
  language: pl
  chunk_size: 200
  top_p: 0.95
  repetition_penalty: 1.2
audio_output:
  format: wav
  sample_rate: 24000
  max_reference_duration_sec: 30
  save_to_disk: false
  crossfade_duration: 0.1
  intro_silence_ms: 0
  inter_chunk_silence_ms: 0
  group_chunks_by_speaker: false
  cleanup_vram_after_job: true
  norm_loudness: true
  prompt_norm_loudness: true
ui_state:
  last_text: "Testowanie czy dzia\u0142a 666 albo 666-NKWD"
  last_voice_mode: clone
  last_predefined_voice: Emily.wav
  last_reference_file: Kustosz.wav
  last_seed: 3000
  last_chunk_size: 220
  last_split_text_enabled: true
  last_speed_factor: 1.0
  last_sentence_pause_ms: 500
  hide_chunk_warning: false
  hide_generation_warning: true
  theme: light
  last_preset_name: "\u26A1 Turbo: Escape Room Panic"
ui:
  title: Chatterbox TTS Server
  show_language_select: true
  max_predefined_voices_in_dropdown: 50
debug:
  save_intermediate_audio: false
